### ISSUE TITLE
Provide "total stats"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#349]
Following up on @joeyh question -- we should do the SUM on the "Size of annexed files" and "Nr of annexed files" first taking max per each ds_id to get a total sum across different dataset IDs.

- [x] Provide the stats through the API
- [ ] Provide the stats through the web UI

**Comment by candleindark** [comment]
We can make these information available through an endpoint such as `dataset-collection-info` or `ds-collection-info`.

**Comment by yarikoptic** [comment]
could include sub-records on different types of URLs, e.g.

```
- types:
   - datalad_datasets:
      count: 1023
      count_clones: 2046
      size: 100000000,
      size_clones: 200000000
      nr_annexed_files: 123
   - pure_annex:
     count: 1
     count_clones: 3
     ...
- summary:
      count: 1023
      count_clones: 2046
      ...
```

and then add basic visualization on the main page, e.g. use empty space we have in the top banner/logo.
